<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.31">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Implementación Numérica y Análisis de Resultados – Aproximación numérica de la solución para ecuaciones diferenciales estocasticas con saltos</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./resultados_simulacion.html" rel="next">
<link href="./metodos-numericos.html" rel="prev">
<link href="./assets/UNACH.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-57fec60b307b2e44e5eedec09c7b3148.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-21591c69f0c38d515a802d0c95f8d624.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-6988b7536e9f70b2e45c63f13c7c4366.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-ba9f47cffa1c95a255a34fae79c2ae38.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<script async="" src="https://hypothes.is/embed.js"></script>
<script>
  window.document.addEventListener("DOMContentLoaded", function (_event) {
    document.body.classList.add('hypothesis-enabled');
  });
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="6&nbsp; Implementación Numérica y Análisis de Resultados – Aproximación numérica de la solución para ecuaciones diferenciales estocasticas con saltos">
<meta property="og:image" content="assets/UNACH.png">
<meta property="og:site_name" content="Aproximación numérica de la solución para ecuaciones diferenciales estocasticas con saltos">
<meta name="twitter:title" content="6&nbsp; Implementación Numérica y Análisis de Resultados – Aproximación numérica de la solución para ecuaciones diferenciales estocasticas con saltos">
<meta name="twitter:image" content="assets/UNACH.png">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar floating quarto-dark"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = true;
    const darkModeDefault = authorPrefersDark;
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./modelo-actuarial.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Implementación Numérica y Análisis de Resultados</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./assets/UNACH.png" alt="" class="sidebar-logo light-content py-0 d-lg-inline d-none">
      <img src="./assets/UNACH.png" alt="" class="sidebar-logo dark-content py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Aproximación numérica de la solución para ecuaciones diferenciales estocasticas con saltos</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/Mara-DL/Tesis_Maestria" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Download" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Download"><i class="bi bi-download"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./Tesis_Maestria_MDL.pdf">
              <i class="bi bi-file-pdf pe-1"></i>
            Download PDF
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./Tesis_Maestria_MDL.epub">
              <i class="bi bi-journal pe-1"></i>
            Download ePub
            </a>
          </li>
      </ul>
    </div>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-1" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-1">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
              <i class="bi bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
      </ul>
    </div>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Alternar modo oscuro"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Inicio</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Introduccion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introducción</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./fundamentos_estocasticos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Resultados técnicos fundamentales</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./edes_saltos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Ecuaciones diferenciales estocásticas.</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./metodos-numericos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Métodos Numéricos para EDES</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./modelo-actuarial.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Implementación Numérica y Análisis de Resultados</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./resultados_simulacion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">resultados_simulacion.html</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./conclusiones.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">conclusiones.html</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Referencias</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#estimación-de-parámetros-para-el-mercado-de-seguros-de-bienes-raíces-mexicano" id="toc-estimación-de-parámetros-para-el-mercado-de-seguros-de-bienes-raíces-mexicano" class="nav-link active" data-scroll-target="#estimación-de-parámetros-para-el-mercado-de-seguros-de-bienes-raíces-mexicano"><span class="header-section-number">6.1</span> Estimación de Parámetros para el mercado de seguros de bienes raíces Mexicano</a>
  <ul class="collapse">
  <li><a href="#función-de-primas-ajustadas-por-inflación-ct" id="toc-función-de-primas-ajustadas-por-inflación-ct" class="nav-link" data-scroll-target="#función-de-primas-ajustadas-por-inflación-ct"><span class="header-section-number">6.1.1</span> Función de Primas Ajustadas por Inflación: <span class="math inline">\(c(t)\)</span></a></li>
  <li><a href="#modelado-de-la-tasa-de-inversión-rt." id="toc-modelado-de-la-tasa-de-inversión-rt." class="nav-link" data-scroll-target="#modelado-de-la-tasa-de-inversión-rt."><span class="header-section-number">6.1.2</span> Modelado de la tasa de inversión: <span class="math inline">\(r(t)\)</span>.</a></li>
  <li><a href="#modelado-de-la-volatilidad-de-inversiones-sigmat." id="toc-modelado-de-la-volatilidad-de-inversiones-sigmat." class="nav-link" data-scroll-target="#modelado-de-la-volatilidad-de-inversiones-sigmat."><span class="header-section-number">6.1.3</span> Modelado de la volatilidad de Inversiones <span class="math inline">\(\sigma(t)\)</span>.</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/Mara-DL/Tesis_Maestria/edit/main/modelo-actuarial.qmd" class="toc-action"><i class="bi bi-github"></i>Editar esta página</a></li><li><a href="https://github.com/Mara-DL/Tesis_Maestria/issues/new" class="toc-action"><i class="bi empty"></i>Informar sobre problema</a></li><li><a href="https://github.com/Mara-DL/Tesis_Maestria/blob/main/modelo-actuarial.qmd" class="toc-action"><i class="bi empty"></i>Ver el código</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Implementación Numérica y Análisis de Resultados</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="estimación-de-parámetros-para-el-mercado-de-seguros-de-bienes-raíces-mexicano" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="estimación-de-parámetros-para-el-mercado-de-seguros-de-bienes-raíces-mexicano"><span class="header-section-number">6.1</span> Estimación de Parámetros para el mercado de seguros de bienes raíces Mexicano</h2>
<section id="función-de-primas-ajustadas-por-inflación-ct" class="level3" data-number="6.1.1">
<h3 data-number="6.1.1" class="anchored" data-anchor-id="función-de-primas-ajustadas-por-inflación-ct"><span class="header-section-number">6.1.1</span> Función de Primas Ajustadas por Inflación: <span class="math inline">\(c(t)\)</span></h3>
<div style="text-align:justify">
<p>La prima base para enero de 2024 se establece en <span class="math inline">\(c_0 = 283.00\)</span>, derivada del consenso de fuentes sectoriales (AMIS, CNSF). El ajuste por inflación se realiza mediante capitalización compuesta: <span id="eq-ajuste_inflacion"><span class="math display">\[ c(t) = c_0 \prod_{i=1}^{t} \left(1 + \pi_i\right),
  \tag{6.1}\]</span></span> donde <span class="math inline">\(\pi_i\)</span> representa la tasa de inflación mensual reportada por el INEGI <span class="citation" data-cites="inegi2024inpc">INEGI (<a href="references.html#ref-inegi2024inpc" role="doc-biblioref">2024</a>)</span>.</p>
</div>
<section id="datos-de-inflación-mensual" class="level4" data-number="6.1.1.1">
<h4 data-number="6.1.1.1" class="anchored" data-anchor-id="datos-de-inflación-mensual"><span class="header-section-number">6.1.1.1</span> Datos de Inflación Mensual</h4>
<div style="text-align:justify">
<p>La Tabla presenta las tasas de inflación utilizadas para el periodo enero 2024 – diciembre 2025. Los datos de 2024 son observados, mientras que las proyecciones de 2025 se basan en el consenso de analistas del Banco de México <span class="citation" data-cites="banxico2024expectativas">Banco de México (<a href="references.html#ref-banxico2024expectativas" role="doc-biblioref">2024</a>)</span>.</p>
</div>
<table class="caption-top table">
<caption>Tasas de inflación mensual en México (variación porcentual del INPC)</caption>
<thead>
<tr class="header">
<th style="text-align: center;">Mes</th>
<th style="text-align: center;">Prima mensual ajustada (MXN)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Ene 2024</td>
<td style="text-align: center;">283.00</td>
</tr>
<tr class="even">
<td style="text-align: center;">Feb 2024</td>
<td style="text-align: center;">284.47</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Mar 2024</td>
<td style="text-align: center;">285.55</td>
</tr>
<tr class="even">
<td style="text-align: center;">Abr 2024</td>
<td style="text-align: center;">286.72</td>
</tr>
<tr class="odd">
<td style="text-align: center;">May 2024</td>
<td style="text-align: center;">288.01</td>
</tr>
<tr class="even">
<td style="text-align: center;">Jun 2024</td>
<td style="text-align: center;">289.42</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Jul 2024</td>
<td style="text-align: center;">291.02</td>
</tr>
<tr class="even">
<td style="text-align: center;">Ago 2024</td>
<td style="text-align: center;">292.79</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Sep 2024</td>
<td style="text-align: center;">294.49</td>
</tr>
<tr class="even">
<td style="text-align: center;">Oct 2024</td>
<td style="text-align: center;">295.87</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Nov 2024</td>
<td style="text-align: center;">297.12</td>
</tr>
<tr class="even">
<td style="text-align: center;">Dic 2024</td>
<td style="text-align: center;">298.28</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Ene 2025</td>
<td style="text-align: center;">299.32</td>
</tr>
<tr class="even">
<td style="text-align: center;">Feb 2025</td>
<td style="text-align: center;">300.82</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Mar 2025</td>
<td style="text-align: center;">301.93</td>
</tr>
<tr class="even">
<td style="text-align: center;">Abr 2025</td>
<td style="text-align: center;">303.14</td>
</tr>
<tr class="odd">
<td style="text-align: center;">May 2025</td>
<td style="text-align: center;">304.47</td>
</tr>
<tr class="even">
<td style="text-align: center;">Jun 2025</td>
<td style="text-align: center;">305.93</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Jul 2025</td>
<td style="text-align: center;">307.55</td>
</tr>
<tr class="even">
<td style="text-align: center;">Ago 2025</td>
<td style="text-align: center;">309.37</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Sep 2025</td>
<td style="text-align: center;">311.10</td>
</tr>
<tr class="even">
<td style="text-align: center;">Oct 2025</td>
<td style="text-align: center;">312.53</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Nov 2025</td>
<td style="text-align: center;">313.81</td>
</tr>
<tr class="even">
<td style="text-align: center;">Dic 2025</td>
<td style="text-align: center;">315.01</td>
</tr>
</tbody>
</table>
<div style="text-align:justify">
<p>Aplicando <a href="#eq-ajuste_inflacion" class="quarto-xref">Ecuación&nbsp;<span>6.1</span></a>, las primas mensuales ajustadas evolucionan de <span class="math inline">\(283.00\)</span> en enero 2024 a <span class="math inline">\(315.01\)</span> en diciembre 2025, representando un incremento acumulado del <span class="math inline">\(11.3\%\)</span>, consistente con la inflación proyectada</p>
</div>
</section>
</section>
<section id="modelado-de-la-tasa-de-inversión-rt." class="level3" data-number="6.1.2">
<h3 data-number="6.1.2" class="anchored" data-anchor-id="modelado-de-la-tasa-de-inversión-rt."><span class="header-section-number">6.1.2</span> Modelado de la tasa de inversión: <span class="math inline">\(r(t)\)</span>.</h3>
<div style="text-align:justify">
<p>Las aseguradoras mexicanas mantienen carteras conservadoras con asignación aproximada de <span class="math inline">\(70\%\)</span> en instrumentos locales (CETES, Mbonos) y <span class="math inline">\(30\%\)</span> en activos globales (<span class="citation" data-cites="cnsf2024panorama">(<a href="references.html#ref-cnsf2024panorama" role="doc-biblioref">CNSF 2024</a>)</span>). Siguiendo el marco regulatorio de la CNSF y la estructura conservadora de las carteras aseguradoras mexicanas (informe anual CNSF), modelamos <span class="math inline">\(r(t)\)</span> como combinación convexa ponderada:</p>
<p><span id="eq-tasa_inversion"><span class="math display">\[r(t) = \rho \cdot r_{\text{CETES}}(t) + (1-\rho) \cdot r_{\text{USD}}(t) \tag{6.2}\]</span></span></p>
<ul>
<li><p><span class="math inline">\(\rho = 0.70\)</span>,</p></li>
<li><p><span class="math inline">\(r_{\text{CETES}}(t)\)</span> la tasa de CETES a 28 días mensualizada,</p></li>
<li><p><span class="math inline">\(r_{\text{USD}}(t)\)</span> el rendimiento de bonos del Tesoro de EE.UU.,</p></li>
<li><p><span class="math inline">\(\rho = 0.75\)</span> refleja la asignación típica de carteras <span class="math inline">\((70-80\%)\)</span> en activos locales según CNSF)</p></li>
</ul>
<p>Para el periodo 2024-2025, con tasas de Banxico estables en <span class="math inline">\(11.0\%\)</span> anual y bonos USD en <span class="math inline">\(4.8\%\)</span> anual:</p>
<p><span class="math display">\[r(t) = 0.75 \cdot \frac{0.110}{12} + 0.25 \cdot \frac{0.048}{12} = 0.007875 \text{ mensual} \quad (9.45\% \text{ anual})\]</span></p>
<p>Este valor se ajusta a <span class="math inline">\(0.78\%\)</span> mensual para incorporar costos operativos y fiscales (<span class="math inline">\(1.5\)</span> p.p. anuales), resultando en un rendimiento neto anual de <span class="math inline">\(8.9\%\)</span>.</p>
</div>
</section>
<section id="modelado-de-la-volatilidad-de-inversiones-sigmat." class="level3" data-number="6.1.3">
<h3 data-number="6.1.3" class="anchored" data-anchor-id="modelado-de-la-volatilidad-de-inversiones-sigmat."><span class="header-section-number">6.1.3</span> Modelado de la volatilidad de Inversiones <span class="math inline">\(\sigma(t)\)</span>.</h3>
<section id="combinación-convexa-de-volatilidades" class="level4" data-number="6.1.3.1">
<h4 data-number="6.1.3.1" class="anchored"><span class="header-section-number">6.1.3.1</span> Combinación Convexa de Volatilidades</h4>
<div style="text-align:justify">
<p>La volatilidad total se estima como combinación ponderada de componentes globales y locales:</p>
<p><span id="eq-volatilidad"><span class="math display">\[\sigma(t) = w_g \cdot \sigma_g(t) + w_l \cdot \sigma_l, \tag{6.3}\]</span></span></p>
<p>Los informes anuales de la CNSF sobre la composición de las inversiones del sector asegurador en México indican que, en promedio, las compañías mantienen:</p>
<ul>
<li><p><span class="math inline">\(30\%\)</span> de sus inversiones en instrumentos del extranjero.</p></li>
<li><p><span class="math inline">\(70\%\)</span> en instrumentos del mercado nacional.</p></li>
</ul>
<p>Dado que no hay datos mensuales oficiales públicos, se asume una asignación constante durante el periodo, basada en el último informe disponible (2023) con <span class="math inline">\(w_g = 0\cdot30\)</span>, <span class="math inline">\(w_l = 0\cdot70\)</span>.</p>
<p>La componente local <span class="math inline">\(\sigma_l(t)\)</span> respecta a la Volatilidad de CETES a 28 días ue es el activo de referencia para las inversiones conservadoras en México, estimada mediante desviación estándar móvil de 30 días de las tasas diarias de Banxico:</p>
<p><span class="math display">\[\sigma_l(t) = 0.05\% \text{ mensual (constante)}\]</span></p>
<p>Mientras que la componente global <span class="math inline">\(\sigma_g(t)\)</span> es dada por la Volatilidad del índice ILS (Artemis.bm), calculada como desviación estándar móvil de <span class="math inline">\(3\)</span> meses de los rendimientos mensuales. Presenta estacionalidad marcada por la temporada de huracanes (junio-noviembre):</p>
<table class="caption-top table">
<caption>Volatilidad Global, <span class="math inline">\(\sigma_g(t)\)</span> mensual</caption>
<thead>
<tr class="header">
<th style="text-align: center;">Mes</th>
<th style="text-align: center;"><span class="math inline">\(\sigma_g(t)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Ene 2024</td>
<td style="text-align: center;">0.08%</td>
</tr>
<tr class="even">
<td style="text-align: center;">Feb 2024</td>
<td style="text-align: center;">0.09%</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Mar 2024</td>
<td style="text-align: center;">0.10%</td>
</tr>
<tr class="even">
<td style="text-align: center;">Abr 2024</td>
<td style="text-align: center;">0.11%</td>
</tr>
<tr class="odd">
<td style="text-align: center;">May 2024</td>
<td style="text-align: center;">0.12%</td>
</tr>
<tr class="even">
<td style="text-align: center;">Jun 2024</td>
<td style="text-align: center;">0.15%</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Jul 2024</td>
<td style="text-align: center;">0.18%</td>
</tr>
<tr class="even">
<td style="text-align: center;">Ago 2024</td>
<td style="text-align: center;">0.35%</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Sep 2024</td>
<td style="text-align: center;">0.30%</td>
</tr>
<tr class="even">
<td style="text-align: center;">Oct 2024</td>
<td style="text-align: center;">0.25%</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Nov 2024</td>
<td style="text-align: center;">0.20%</td>
</tr>
<tr class="even">
<td style="text-align: center;">Dic 2024</td>
<td style="text-align: center;">0.18%</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Ene 2025</td>
<td style="text-align: center;">0.16%</td>
</tr>
<tr class="even">
<td style="text-align: center;">Feb 2025</td>
<td style="text-align: center;">0.14%</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Mar 2025</td>
<td style="text-align: center;">0.13%</td>
</tr>
<tr class="even">
<td style="text-align: center;">Abr 2025</td>
<td style="text-align: center;">0.14%</td>
</tr>
<tr class="odd">
<td style="text-align: center;">May 2025</td>
<td style="text-align: center;">0.16%</td>
</tr>
<tr class="even">
<td style="text-align: center;">Jun 2025</td>
<td style="text-align: center;">0.20%</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Jul 2025</td>
<td style="text-align: center;">0.25%</td>
</tr>
<tr class="even">
<td style="text-align: center;">Ago 2025</td>
<td style="text-align: center;">0.22%</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Sep 2025</td>
<td style="text-align: center;">0.28%</td>
</tr>
<tr class="even">
<td style="text-align: center;">Oct 2025</td>
<td style="text-align: center;">0.24%</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Nov-25</td>
<td style="text-align: center;">0.20%</td>
</tr>
<tr class="even">
<td style="text-align: center;">Dic 2025</td>
<td style="text-align: center;">0.18%</td>
</tr>
</tbody>
</table>
<p>La volatilidad total mensual resultante es :</p>
<table class="caption-top table">
<caption>Volatilidad Total, <span class="math inline">\(\sigma\)</span> mensual.</caption>
<thead>
<tr class="header">
<th style="text-align: center;">Mes</th>
<th style="text-align: center;"><span class="math inline">\(\sigma_g\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\sigma_l\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\sigma(t)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Ene 2024</td>
<td style="text-align: center;">0.08</td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">0.059</td>
</tr>
<tr class="even">
<td style="text-align: center;">Feb 2024</td>
<td style="text-align: center;">0.09</td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">0.062</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Mar 2024</td>
<td style="text-align: center;">0.10</td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">0.065</td>
</tr>
<tr class="even">
<td style="text-align: center;">Abr 2024</td>
<td style="text-align: center;">0.11</td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">0.068</td>
</tr>
<tr class="odd">
<td style="text-align: center;">May 2024</td>
<td style="text-align: center;">0.12</td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">0.071</td>
</tr>
<tr class="even">
<td style="text-align: center;">Jun 2024</td>
<td style="text-align: center;">0.15</td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">0.080</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Jul 2024</td>
<td style="text-align: center;">0.18</td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">0.089</td>
</tr>
<tr class="even">
<td style="text-align: center;">Ago 2024</td>
<td style="text-align: center;">0.35</td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">0.140</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Sep 2024</td>
<td style="text-align: center;">0.30</td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">0.125</td>
</tr>
<tr class="even">
<td style="text-align: center;">Oct 2024</td>
<td style="text-align: center;">0.25</td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">0.110</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Nov 2024</td>
<td style="text-align: center;">0.20</td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">0.095</td>
</tr>
<tr class="even">
<td style="text-align: center;">Dic 2024</td>
<td style="text-align: center;">0.18</td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">0.089</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Ene 2025</td>
<td style="text-align: center;">0.16</td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">0.083</td>
</tr>
<tr class="even">
<td style="text-align: center;">Feb 2025</td>
<td style="text-align: center;">0.14</td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">0.077</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Mar 2025</td>
<td style="text-align: center;">0.13</td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">0.074</td>
</tr>
<tr class="even">
<td style="text-align: center;">Abr 2025</td>
<td style="text-align: center;">0.14</td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">0.077</td>
</tr>
<tr class="odd">
<td style="text-align: center;">May 2025</td>
<td style="text-align: center;">0.16</td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">0.083</td>
</tr>
<tr class="even">
<td style="text-align: center;">Jun 2025</td>
<td style="text-align: center;">0.20</td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">0.095</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Jul 2025</td>
<td style="text-align: center;">0.25</td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">0.110</td>
</tr>
<tr class="even">
<td style="text-align: center;">Ago 2025</td>
<td style="text-align: center;">0.22</td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">0.101</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Sep 2025</td>
<td style="text-align: center;">0.28</td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">0.119</td>
</tr>
<tr class="even">
<td style="text-align: center;">Oct 2025</td>
<td style="text-align: center;">0.24</td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">0.107</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Nov-25</td>
<td style="text-align: center;">0.20</td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">0.095</td>
</tr>
<tr class="even">
<td style="text-align: center;">Dic 2025</td>
<td style="text-align: center;">0.18</td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">0.089</td>
</tr>
</tbody>
</table>
<p>con promedio anual <span class="math inline">\(\bar \sigma= 0.092\%\)</span> con picos superiores a <span class="math inline">\(0.14\%\)</span> en meses de alta actividad catastrófica.</p>
<section id="función-de-costos-de-saltos-eventos-meteorológicos-y-sísmicos." class="level3" data-number="6.1.4">
<h3 data-number="6.1.4" class="anchored" data-anchor-id="función-de-costos-de-saltos-eventos-meteorológicos-y-sísmicos."><span class="header-section-number">6.1.4</span> Función de Costos de Saltos: Eventos Meteorológicos y Sísmicos.</h3>
<p>El proceso de siniestros <span class="math inline">\(S(t)\)</span> se descompone en dos componentes independientes que reflejan la naturaleza bimodal del riesgo en México:</p>
<p><span class="math display">\[S(t) = S_{\text{meteo}}(t) + S_{\text{sismo}}(t) = \sum_{i=1}^{N_{\text{meteo}}(t)} Y_i^{\text{meteo}} + \sum_{j=1}^{N_{\text{sismo}}(t)} Y_j^{\text{sismo}}\]</span></p>
<p>donde <span class="math inline">\(N_{\text{meteo}}(t)\)</span> sigue un proceso de Poisson no homogéneo con intensidad <span class="math inline">\(\lambda{\text{meteo}}(t) = \lambda_{\text{meteo}}^{\text{anual}} \cdot \phi(t)), siendo (\phi(t)\)</span> una función estacional mensual normalizada <span class="math inline">\(\left(\frac{1}{12}\int_0^{12}\phi(s)ds = 1\right)\)</span>, y <span class="math inline">\(N{\text{sismo}}(t)\)</span> es un proceso de Poisson homogéneo con intensidad constante (_{}) debido a la ausencia de estacionalidad significativa en la ocurrencia de sismos de magnitud relevante para siniestros asegurados.</p>
<section id="estimación-de-la-intensidad-de-siniestro." class="level4" data-number="6.1.4.1">
<h4 data-number="6.1.4.1" class="anchored" data-anchor-id="estimación-de-la-intensidad-de-siniestro."><span class="header-section-number">6.1.4.1</span> Estimación de la Intensidad de Siniestro.</h4>
<section id="componente-hidrometeorológico" class="level5" data-number="6.1.4.1.1">
<h5 data-number="6.1.4.1.1" class="anchored" data-anchor-id="componente-hidrometeorológico"><span class="header-section-number">6.1.4.1.1</span> Componente Hidrometeorológico</h5>
<p>La intensidad mensual <span class="math inline">\(\lambda_{\text{meteo}}(m)\)</span> para el mes <span class="math inline">\(m \in {1,\dots,12}\)</span> se estima mediante:</p>
<p><span class="math display">\[\lambda_{\text{meteo}}(m) = \frac{\lambda_{\text{meteo}}^{\text{anual}}}{12} \cdot \phi(m)\]</span></p>
<p>donde <span class="math inline">\(\lambda_{\text{meteo}}^{\text{anual}} = 8.0\)</span> eventos/año se calibra a partir de los registros históricos de la CONAGUA de fenómenos hidrometeorológicos que generaron reclamaciones superiores a USD <span class="math inline">\(100,000\)</span> en viviendas aseguradas en la CDMX. La función estacional <span class="math inline">\(\phi(m)\)</span> se obtiene normalizando los datos mensuales de frecuencia relativa:</p>
<p><span class="math display">\[\phi(m) = \frac{f_m}{\frac{1}{12}\sum_{k=1}^{12} f_k}, \quad f = [0.3, 0.3, 0.4, 0.6, 1.0, 1.8, 2.2, 2.5, 2.8, 2.3, 1.2, 0.5]\]</span></p>
<p>Esta calibración refleja el pico estacional en septiembre (huracanes y lluvias intensas) y el mínimo en enero-febrero, consistente con el patrón climatológico del centro de México.</p>
</section>
<section id="componente-sísmico" class="level5" data-number="6.1.4.1.2">
<h5 data-number="6.1.4.1.2" class="anchored" data-anchor-id="componente-sísmico"><span class="header-section-number">6.1.4.1.2</span> Componente Sísmico</h5>
<p>Para sismos, utilizamos <span class="math inline">\(\lambda_{\text{sismo}} = 0.08\)</span> eventos/año, derivado del catálogo del Servicio Sismológico Nacional (SSN) considerando únicamente eventos con magnitud <span class="math inline">\(M_w \geq 6.0\)</span> y epicentro a menos de <span class="math inline">\(300 km\)</span> de la CDMX que históricamente han generado siniestralidad asegurada significativa (ej. sismos de 1985, 2017). Dado que la ocurrencia de sismos no presenta estacionalidad estadísticamente significativa <span class="math inline">\((p\text{-valor} &gt; 0.15)\)</span> en test de Kolmogorov-Smirnov para uniformidad mensual), mantenemos intensidad constante:</p>
<p><span class="math display">\[\lambda_{\text{sismo}}(m) = \frac{\lambda_{\text{sismo}}}{12} = 0.0067 \text{ eventos/mes}\]</span></p>
</section>
</section>
<section id="estimación-de-la-distribución-de-severidad." class="level4" data-number="6.1.4.2">
<h4 data-number="6.1.4.2" class="anchored" data-anchor-id="estimación-de-la-distribución-de-severidad."><span class="header-section-number">6.1.4.2</span> Estimación de la Distribución de Severidad.</h4>
<section id="severidad-meteorológica" class="level5" data-number="6.1.4.2.1">
<h5 data-number="6.1.4.2.1" class="anchored" data-anchor-id="severidad-meteorológica"><span class="header-section-number">6.1.4.2.1</span> Severidad meteorológica</h5>
<p>Modelamos la severidad de los siniestros hidrometeorológicos $Y_{\text{meteo}} $ mediante una distribución normal truncada en <span class="math inline">\([0, \infty)\)</span>, denotada como</p>
<p><span class="math display">\[Y_{\text{meteo}} \sim \mathcal{N}_+( \mu, \sigma^2 ),\]</span></p>
<p>donde <span class="math inline">\(\mathcal{N}_+\)</span> indica una normal truncada inferiormente en <span class="math inline">\(0.\)</span></p>
<p>Los parámetros <span class="math inline">\(\mu\)</span> y <span class="math inline">\(\sigma\)</span> se estiman por máxima verosimilitud a partir de las <span class="math inline">\(1,247\)</span> reclamaciones hidrometeorológicas reportadas en el FES 2024 para la Ciudad de México:</p>
<p><span class="math display">\[\hat{\mu} = 12.5 \quad (\text{IC}_{95\%}: [12.3,\, 12.7]), \qquad\hat{\sigma} = 1.0 \quad (\text{IC}_{95\%}: [0.92,\, 1.08]).\]</span></p>
<p>Estos valores corresponden a la media y desviación estándar de la distribución subyacente no truncada (es decir, la normal que se trunca para obtener la distribución de severidad positiva). El valor esperado de una normal truncada en <span class="math inline">\([0,\infty)\)</span> es:</p>
<p><span class="math display">\[\mathbb{E}[Y_{\text{meteo}}] = \mu + \sigma \cdot \frac{\varphi(\alpha)}{1 - \Phi(\alpha)}, \qquad \alpha = -\frac{\mu}{\sigma},\]</span></p>
<p>donde <span class="math inline">\(\varphi\)</span> y <span class="math inline">\(\Phi\)</span> son la función de densidad y la función de distribución acumulada de la normal estándar, respectivamente.</p>
</section>
<section id="severidad-sísmica." class="level5" data-number="6.1.4.2.2">
<h5 data-number="6.1.4.2.2" class="anchored" data-anchor-id="severidad-sísmica."><span class="header-section-number">6.1.4.2.2</span> Severidad sísmica.</h5>
<p>Para los siniestros sísmicos, adoptamos también una distribución normal truncada en <span class="math inline">\([0, \infty)\)</span>, es decir:</p>
<p><span class="math display">\[Y_{\text{sismo}} \sim \mathcal{N}_+(\mu_s, \sigma_s^2).\]</span></p>
<p>Los parámetros se estiman por máxima verosimilitud robusta (M-estimador o regresión cuantílica) sobre las 43 reclamaciones sísmicas registradas en el periodo 2000–2023 en la CDMX:</p>
<p><span class="math display">\[\hat{\mu}_s = \ln(1{,}750{,}000) \approx 14.37, \qquad\hat{\sigma}_s = 0.65 \quad (\text{IC}_{95\%}: [0.55,\, 0.75]).\]</span></p>
<p>Estos valores se obtienen al ajustar una normal en escala logarítmica (como es común en modelado de severidad), y luego se interpreta como una normal truncada en la escala original. Nuevamente, dado que <span class="math inline">\(\mu_s / \sigma_s \approx 22.1 \gg 1\)</span>, la probabilidad de que la variable no truncada sea negativa es astronómicamente pequeña <span class="math inline">\((&lt;10^{-100})\)</span>, por lo que la truncación no modifica significativamente la media.</p>
<p>El valor esperado es entonces aproximadamente:</p>
<p><span class="math display">\[\mathbb{E}[Y_{\text{sismo}}] \approx \exp\!\left(\mu_s + \frac{\sigma_s^2}{2}\right)= \exp\!\left(14.37 + \frac{0.65^2}{2}\right)= \exp(14.37 + 0.21125) = \exp(14.58125) \approx \text{USD } 2{,}160{,}000.\]</span></p>
<p>Sin embargo, si queremos mantener coherencia con el valor anterior de USD 1,750,000 con <span class="math inline">\(\alpha=1.4\)</span>, <span class="math inline">\(x_{\min}=500{,}000\)</span>, podemos calibrar la normal truncada para que tenga exactamente esa media. Resolvemos:</p>
<p><span class="math display">\[\mathbb{E}[Y] = \mu + \sigma \cdot \lambda(\alpha) = 1{,}750{,}000,\]</span></p>
<p>con <span class="math inline">\(\alpha = -\mu/\sigma\)</span>, y <span class="math inline">\(\lambda(\alpha) = \varphi(\alpha)/(1-\Phi(\alpha))\)</span>. Dado que <span class="math inline">\(\mu\)</span> y <span class="math inline">\(\sigma\)</span> están en escala <em>lineal</em> (no log), proponemos una calibración directa:</p>
<ul>
<li><p>Supongamos que la severidad sísmica tiene media <span class="math inline">\(\mu_s = 1{,}750{,}000\)</span> y desviación estándar <span class="math inline">\(\sigma_s = 875{,}000\)</span> (coeficiente de variación ≈ 0.5), lo cual es consistente con la dispersión observada en eventos catastróficos (ej. sismo 2017: reclamaciones entre <span class="math inline">\(USD 0.8M y 3.2M)\)</span>.</p></li>
<li><p>Entonces, la distribución normal truncada <span class="math inline">\(\mathcal{N}_+(1{,}750{,}000,; 875{,}000^2)\)</span> tiene:</p>
<p><span class="math display">\[\alpha = -\frac{1{,}750{,}000}{875{,}000} = -2.0,  \quad  \lambda(\alpha) = \frac{\varphi(-2)}{1-\Phi(-2)} = \frac{0.0540}{0.9772} \approx 0.0553,\]</span></p>
<p>y por tanto</p>
<p><span class="math display">\[\mathbb{E}[Y] = \mu + \sigma \lambda(\alpha) = 1{,}750{,}000 + 875{,}000 \cdot 0.0553 \approx 1{,}798{,}400,\]</span></p>
<p>muy cercano a 1.75M. Si ajustamos ligeramente <span class="math inline">\(\mu = 1{,}742{,}000\)</span>, obtenemos <span class="math inline">\(\mathbb{E}[Y] \approx 1{,}750{,}000\)</span>.</p></li>
</ul>
<p>Así, proponemos finalmente:</p>
<p><span class="math display">\[Y_{\text{sismo}} \sim \mathcal{N}_+\bigl(\mu_s = 1{,}742{,}000,\; \sigma_s = 875{,}000\bigr),\]</span></p>
<p>con <span class="math inline">\(\mathbb{E}[Y_{\text{sismo}}] = \text{USD } 1{,}750{,}000\)</span>, y coeficiente de variación <span class="math inline">\(= 0.50\)</span>.</p>
</section>
</section>
</section>
<section id="aproximación-numérica-del-modelo-de-crámer-lundberg-extendido" class="level3" data-number="6.1.5">
<h3 data-number="6.1.5" class="anchored" data-anchor-id="aproximación-numérica-del-modelo-de-crámer-lundberg-extendido"><span class="header-section-number">6.1.5</span> Aproximación numérica del modelo de Crámer Lundberg extendido</h3>
<p>Consideramos el proceso de reservas bajo el modelo extendido de Cramér-Lundberg con inversión estocástica y saltos reescribimos <a href="edes_saltos.html#eq-modelo_extendido" class="quarto-xref">Ecuación&nbsp;<span>4.10</span></a> en forma diferencial estocástica:</p>
<p><span id="eq-eds-completa"><span class="math display">\[dX_t = \underbrace{\left[c(t) + r(t)X_t - \lambda_{\text{meteo}}(t)\mathbb{E}[Y^{\text{meteo}}_t \mid \mathcal{F}_t] - \lambda_{\text{sismo}}\mathbb{E}[Y^{\text{sismo}}_t \mid \mathcal{F}_t]\right]}_{\mu(t,X_t)}dt + \underbrace{\sigma(t)X_t}_{\sigma(t,X_t)}dW_t - dJ_t \tag{6.4}\]</span></span> La compensación <span class="math inline">\(\lambda \mathbb{E}[Y \mid \mathcal{F}_t]\)</span> garantiza que el proceso sin saltos reales sea una semimartingala con la deriva correcta, esencial para la convergencia del esquema numérico.</p>
<p>Se ha desarrollado un modelo Cramér-Lundberg extendido para aproximar las reservas de una aseguradora de vivienda en la Ciudad de México. Este modelo incorpora parámetros dependientes del tiempo, primas ajustadas por inflación (Sección 3.1), tasas de interés estocásticas (Sección 3.2), volatilidad mediante combinación convexa (Sección 3.3) y un proceso de saltos compuesto que modela siniestros catastróficos meteorológicos y sísmicos con intensidades estacionales (Sección 3.4.1).</p>
<p>Dada la complejidad de la ecuación diferencial estocástica con saltos resultante (EDE-S), cuya solución analítica no es viable ante la no estacionariedad de los parámetros y la estructura de saltos, se requiere métodos numéricos robustos.</p>
<p>Para la simulación, discretizamos con paso <span class="math inline">\(\Delta t = 1/12\)</span> (mensual) y consideramos dos esquemas numéricos.</p>
<section id="implementación-numérica-métodos-milstein-y-semi-implícito." class="level4" data-number="6.1.5.1">
<h4 data-number="6.1.5.1" class="anchored" data-anchor-id="implementación-numérica-métodos-milstein-y-semi-implícito."><span class="header-section-number">6.1.5.1</span> Implementación Numérica Métodos Milstein y Semi-Implícito.</h4>
<p>Presentando el algoritmo de Milstein compensado (<a href="metodos-numericos.html#sec-EDESJs" class="quarto-xref"><span>Sección 5.2</span></a>), escrito en lenguaje natural estructurado (es decir, como un pseudocódigo), diseñado específicamente para aproximar soluciones de ecuaciones diferenciales estocásticas (EDS) con difusión y salto(<a href="metodos-numericos.html#sec-EDESJs" class="quarto-xref"><span>Sección 5.2</span></a>), como las que surgen en el modelo de Cramér–Lundberg (<a href="edes_saltos.html#eq-modelo_extendido" class="quarto-xref">Ecuación&nbsp;<span>4.10</span></a>) por ejemplo, con componentes de procesos compuestos de Poisson)</p>
<p>El pseudocódigo siguiente está pensado para ser puente conceptual entre la teoría y la implementación, y se enfoca en la versión compensada (es decir, usando el proceso de salto compensado <span class="math inline">\(\tilde{N} = N_t - \lambda t\)</span>) para garantizar que el término de salto tenga esperanza cero y sea adecuado para esquemas numéricos estables.</p>
</section>
<section id="pseudocódigo-esquema-de-milstein-compensado-para-eds-con-difusión-y-salto." class="level4" data-number="6.1.5.2">
<h4 data-number="6.1.5.2" class="anchored" data-anchor-id="pseudocódigo-esquema-de-milstein-compensado-para-eds-con-difusión-y-salto."><span class="header-section-number">6.1.5.2</span> Pseudocódigo: Esquema de Milstein Compensado para EDS con Difusión y Salto.</h4>
<pre class="{# -*- coding: utf-8 -*-}"><code>"""
Implementación Completa del Método Milstein para SDE con Saltos Compensados.
Incluye simulación histórica, pronóstico, detección de saltos y visualización.
"""

import numpy as np
import plotly.graph_objects as go

# -----------------------------
# PARTE 0: CONFIGURACIÓN INICIAL
# -----------------------------
np.random.seed(2026)
tipo_cambio = 18.5
dt = 1 / 365  # Paso diario

# -----------------------------
# PARTE 1: CALIBRACIÓN DE PARÁMETROS
# -----------------------------

N_polizas = 6800
prima_base_por_poliza = 850.00
delta = 0.0015
X0_hist = 500e6  # Capital inicial histórico
U0_forecast = 520e6  # Capital inicial para pronóstico (ejemplo)

# Inflación y primas
inflacion_mensual = np.array([
    0.52, 0.38, 0.38, 0.41, 0.45, 0.49, 0.55, 0.61, 0.58, 0.47, 0.42, 0.39,
    0.35, 0.50, 0.37, 0.40, 0.44, 0.48, 0.53, 0.59, 0.56, 0.46, 0.41, 0.38
]) / 100.0

g = inflacion_mensual + delta
cum_g = np.cumsum(g)
primas_por_poliza_mxn = prima_base_por_poliza * np.exp(cum_g)
primas_totales_mxn = primas_por_poliza_mxn * N_polizas
c_t_mensual_usd = primas_totales_mxn / tipo_cambio
c_t_mensual_usd = np.round(c_t_mensual_usd, 2)

# --- Intensidades calibradas ---
lambda_meteo_annual = 6.0
lambda_sismo = 0.15 #0.08
seasonal_raw = [0.3, 0.3, 0.4, 0.6, 1.0, 1.8, 2.2, 2.5, 2.8, 2.3, 1.2, 0.5]
seasonal_norm = np.array(seasonal_raw) / np.mean(seasonal_raw)

# --- Parámetros de severidad (ahora dependientes del estado) ---
ceiling_per_policy = 5000.0
COEF_VARIACION_METEO = 0.1
COEF_VARIACION_SISMO = 0.2

# --- Rendimiento y volatilidad ---
r_t_mensual = np.array([
    0.606, 0.602, 0.600, 0.597, 0.593, 0.589,
    0.586, 0.582, 0.578, 0.574, 0.570, 0.566,
    0.562, 0.559, 0.555, 0.551, 0.547, 0.543,
    0.539, 0.535, 0.532, 0.528, 0.524, 0.520
]) / 100.0

sigma_t_mensual = np.array([
    0.44, 0.47, 0.50, 0.53, 0.59, 0.74,
    0.89, 1.34, 1.19, 0.98, 0.74, 0.68,
    0.65, 0.60, 0.58, 0.60, 0.65, 0.74,
    0.89, 0.82, 0.95, 0.86, 0.74, 0.68
]) / 100.0

# -----------------------------
# PARTE 2: FUNCIÓN AUXILIAR PARA LA COMPENSACIÓN
# -----------------------------

def expected_loss_per_event(deviation, mu_per_policy, pct_low, pct_high, n_pols):
    """
    Calcula la pérdida esperada por un evento dado el estado actual.
    """
    E_pct = (pct_low + pct_high) / 2
    n_aff_mean = n_pols * E_pct #Valor esperado de la distribución uniforme para el número de afectados
    mu_per_policy = deviation
    return n_aff_mean * mu_per_policy

# -----------------------------
# PARTE 3: SIMULACIÓN HISTÓRICA (Ene 2024 - Dic 2025) CON COMPENSACIÓN
# -----------------------------

T_hist = 2.0
N_hist = int(T_hist / dt)
N_sim_hist = 500

dias_hist = np.linspace(0, T_hist, N_hist + 1)
meses_enteros = np.arange(24)

r_hist = np.interp(dias_hist[:-1], meses_enteros, r_t_mensual)
sigma_hist = np.interp(dias_hist[:-1], meses_enteros, sigma_t_mensual)
c_hist = np.interp(dias_hist[:-1], meses_enteros, c_t_mensual_usd)

X_hist = np.zeros((N_sim_hist, N_hist + 1))
X_hist[:, 0] = X0_hist

print("Simulando periodo histórico (Ene 2024 - Dic 2025) con Milstein y compensación...")

for sim in range(N_sim_hist):
    for i in range(N_hist):
        t_dia = dias_hist[i]
        mes_actual = int(t_dia) % 12

        lam_meteo_dia = (lambda_meteo_annual / 365) * seasonal_norm[mes_actual]
        lam_sismo_dia = lambda_sismo / 365

        n_meteo = np.random.poisson(lam_meteo_dia)
        n_sismo = np.random.poisson(lam_sismo_dia)

        x_current = X_hist[sim, i]
        deviation = (abs(x_current - X0_hist))/N_polizas
        if deviation &gt; ceiling_per_policy:
            deviation = ceiling_per_policy

        total_jump = 0.0
        compensacion = 0.0

        # --- Eventos Meteorológicos ---
        if n_meteo &gt; 0:
            pct_affected = np.random.uniform(0.005, 0.02)
            n_affected = max(1, int(N_polizas * pct_affected))
            mu_per_policy = deviation
            sigma_per_policy = COEF_VARIACION_METEO * mu_per_policy
            losses = np.random.normal(mu_per_policy, sigma_per_policy, size=n_affected)
            losses = np.clip(losses, 0.0, None)
            total_jump += np.sum(losses)

        # Compensación meteorológica
        E_loss_meteo = expected_loss_per_event(
            deviation, mu_per_policy, 0.005, 0.02, N_polizas
        )
        compensacion += (-1)*lam_meteo_dia * E_loss_meteo

        # --- Eventos Sísmicos ---
        if n_sismo &gt; 0:
            pct_affected = np.random.uniform(0.01, 0.10)
            n_affected = max(1, int(N_polizas * pct_affected))
            mu_per_policy = deviation
            sigma_per_policy = COEF_VARIACION_SISMO * mu_per_policy
            losses = np.random.normal(mu_per_policy, sigma_per_policy, size=n_affected)
            losses = np.clip(losses, 0.0, None)
            total_jump += np.sum(losses)

        # Compensación sísmica
        E_loss_sismo = expected_loss_per_event(
            deviation, mu_per_policy, 0.01, 0.10, N_polizas
        )
        compensacion += (-1)*lam_sismo_dia * E_loss_sismo

        # --- Actualización con Milstein + Compensación ---
        dW = np.sqrt(dt) * np.random.randn()
        drift_base = c_hist[i] * dt + r_hist[i] * x_current * dt
        drift_compensado = drift_base + compensacion
        diffusion = sigma_hist[i] * x_current * dW
        milstein_corr = 0.5 * (sigma_hist[i]**2) * x_current * (dW**2 - dt)
        X_hist[sim, i+1] = x_current + drift_compensado + diffusion + milstein_corr - total_jump

U0_forecast = np.median(X_hist[:, -1])
print(f"Condición inicial para pronóstico (Ene 2026): ${U0_forecast/1e6:.2f}M")
# -----------------------------
# PARTE 4: SIMULACIÓN DEL PRONÓSTICO (Ene 2026) CON COMPENSACIÓN
# -----------------------------

forecast_days = 30
mes_pronostico = 0

# Promedios para enero (mes 0 y mes 12)
c_ene_avg = (c_t_mensual_usd[0] + c_t_mensual_usd[12]) / 2
r_ene_avg = (r_t_mensual[0] + r_t_mensual[12]) / 2
sigma_ene_avg = (sigma_t_mensual[0] + sigma_t_mensual[12]) / 2
sf_ene_avg = seasonal_norm[0]  # Enero es el mes 0

c_daily_fc = np.full(forecast_days, c_ene_avg / 30.0)
r_daily_fc = np.full(forecast_days, r_ene_avg)
sigma_daily_fc = np.full(forecast_days, sigma_ene_avg)
lambda_meteo_dia_fc = (lambda_meteo_annual / 365) * sf_ene_avg
lambda_sismo_dia_fc = lambda_sismo / 365

np.random.seed(2027)
N_sim_fc = 1000
U_forecast = np.zeros((N_sim_fc, forecast_days + 1))
U_forecast[:, 0] = U0_forecast

print("Simulando pronóstico para Enero 2026 con Milstein y compensación...")

for sim in range(N_sim_fc):
    for i in range(forecast_days):
        u_current = U_forecast[sim, i]
        deviation = (abs(u_current - U0_forecast))/N_polizas
        if deviation &gt; ceiling_per_policy:
            deviation = ceiling_per_policy
        total_jump = 0.0
        compensacion = 0.0

        # --- Simular eventos ---
        n_meteo = np.random.poisson(lambda_meteo_dia_fc)
        n_sismo = np.random.poisson(lambda_sismo_dia_fc)

        # --- Eventos Meteorológicos ---
        if n_meteo &gt; 0:
            pct_affected = np.random.uniform(0.005, 0.02)
            n_affected = max(1, int(N_polizas * pct_affected))
            mu_per_policy = deviation
            sigma_per_policy = COEF_VARIACION_METEO * mu_per_policy
            losses = np.random.normal(mu_per_policy, sigma_per_policy, size=n_affected)
            losses = np.clip(losses, 0.0, None)
            total_jump += np.sum(losses)

        # Compensación meteorológica
        E_loss_meteo = expected_loss_per_event(
            deviation, mu_per_policy, 0.005, 0.02, N_polizas
        )
        compensacion += (-1)*lambda_meteo_dia_fc * E_loss_meteo

        # --- Eventos Sísmicos ---
        if n_sismo &gt; 0:
            pct_affected = np.random.uniform(0.01, 0.10)
            n_affected = max(1, int(N_polizas * pct_affected))
            mu_per_policy = deviation
            sigma_per_policy = COEF_VARIACION_SISMO * mu_per_policy
            losses = np.random.normal(mu_per_policy, sigma_per_policy, size=n_affected)
            losses = np.clip(losses, 0.0, None)
            total_jump += np.sum(losses)

        # Compensación sísmica
        E_loss_sismo = expected_loss_per_event(
            deviation, mu_per_policy,  0.01, 0.10, N_polizas
        )
        compensacion +=(-1)* lambda_sismo_dia_fc * E_loss_sismo

        # --- Actualización con Milstein + Compensación ---
        dW = np.sqrt(dt) * np.random.randn()
        drift_base = c_daily_fc[i] * dt + r_daily_fc[i] * u_current * dt
        drift_compensado = drift_base + compensacion
        diffusion = sigma_daily_fc[i] * u_current * dW
        milstein_corr = 0.5 * (sigma_daily_fc[i]**2) * u_current * (dW**2 - dt)
        U_forecast[sim, i+1] = u_current + drift_compensado + diffusion + milstein_corr - total_jump

# -----------------------------
# PARTE 5: CÁLCULO DE ESTADÍSTICAS
# -----------------------------

median_hist = np.median(X_hist, axis=0) / 1e6
p05_hist = np.percentile(X_hist, 5, axis=0) / 1e6
p95_hist = np.percentile(X_hist, 95, axis=0) / 1e6

median_fc = np.median(U_forecast, axis=0) / 1e6
p05_fc = np.percentile(U_forecast, 5, axis=0) / 1e6
p95_fc = np.percentile(U_forecast, 95, axis=0) / 1e6

# -----------------------------
# PARTE 6: DETECCIÓN DE SALTOS EN LA MEDIANA
# -----------------------------

def detect_jumps(median_series):
    """Detecta saltos en una serie temporal usando umbral de 3 desviaciones estándar."""
    median_usd = median_series * 1e6
    log_returns = np.log(median_usd[1:] / median_usd[:-1])
    threshold = 3 * np.std(log_returns)
    jump_flags = np.abs(log_returns) &gt; threshold
    jump_indices = np.where(jump_flags)[0] + 1
    jump_times = np.arange(len(median_series))[jump_indices]
    jump_values = median_series[jump_indices]
    return jump_times, jump_values

# Detectar saltos
time_historical = np.arange(N_hist + 1)
jump_times_hist, jump_values_hist = detect_jumps(median_hist)

time_forecast = np.arange(N_hist, N_hist + forecast_days + 1)
jump_times_fc, jump_values_fc = detect_jumps(median_fc)

# -----------------------------
# PARTE 7: GRÁFICA INTERACTIVA CON PLOTLY
# -----------------------------

fig = go.Figure()

# Área de incertidumbre histórico
fig.add_trace(go.Scatter(
    x=np.concatenate([time_historical, time_historical[::-1]]),
    y=np.concatenate([p95_hist, p05_hist[::-1]]),
    fill='toself',
    fillcolor='rgba(144, 238, 144, 0.3)',
    line=dict(color='rgba(144, 238, 144, 0)'),
    hoverinfo="skip",
    showlegend=True,
    name='Histórico (5%-95%)'
))

# Mediana histórica
fig.add_trace(go.Scatter(
    x=time_historical,
    y=median_hist,
    mode='lines',
    line=dict(color='darkgreen', width=2.5),
    name='Mediana (Histórico)'
))

# Saltos en la mediana histórica
if len(jump_times_hist) &gt; 0:
    fig.add_trace(go.Scatter(
        x=jump_times_hist,
        y=jump_values_hist,
        mode='markers',
        marker=dict(color='red', size=8, symbol='x'),
        name='Saltos (Histórico)'
    ))

# Área de incertidumbre del pronóstico
fig.add_trace(go.Scatter(
    x=np.concatenate([time_forecast, time_forecast[::-1]]),
    y=np.concatenate([p95_fc, p05_fc[::-1]]),
    fill='toself',
    fillcolor='rgba(205, 92, 92, 0.25)',
    line=dict(color='rgba(205, 92, 92, 0)'),
    hoverinfo="skip",
    showlegend=True,
    name='Pronóstico (5%-95%)'
))

# Mediana del pronóstico
fig.add_trace(go.Scatter(
    x=time_forecast,
    y=median_fc,
    mode='lines',
    line=dict(color='darkred', width=2.5),
    name='Mediana (Pronóstico)'
))

# Saltos en la mediana del pronóstico
if len(jump_times_fc) &gt; 0:
    fig.add_trace(go.Scatter(
        x=jump_times_fc + N_hist,
        y=jump_values_fc,
        mode='markers',
        marker=dict(color='blue', size=10, symbol='star'),
        name='Saltos (Pronóstico)'
    ))

# Línea divisoria
fig.add_vline(x=N_hist, line_dash="dash", line_color="black", annotation_text="Inicio del Pronóstico")

# Configuración final
months_full = [f"{y}-{m:02d}" for y in [2024, 2025] for m in range(1, 13)]
month_labels = months_full[::2]
month_ticks = np.arange(0, 720, 60)
all_ticks = np.concatenate([month_ticks, [N_hist + 30]])
all_labels = month_labels + ["2026-01"]

fig.update_layout(
    title='Reservas de la Aseguradora: Histórico (2024–2025) + Pronóstico Ene 2026&lt;br&gt;'
          '&lt;sup&gt;Modelo Cramér-Lundberg con Milstein, Siniestros Realistas y Detección de Saltos (México)&lt;/sup&gt;',
    xaxis_title="Tiempo",
    yaxis_title="Reservas (Millones USD)",
    xaxis=dict(tickmode='array', tickvals=all_ticks, ticktext=all_labels, tickangle=45),
    legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
    hovermode="x unified",
    template="plotly_white",
    height=600,
    width=1000
)

fig.show()

# -----------------------------
# PARTE 8: RESUMEN DEL PRONÓSTICO
# -----------------------------

print(f"\nPronóstico para Enero 2026:")
print(f"- Reserva inicial: ${U0_forecast/1e6:.2f}M")
print(f"- Mediana final:  ${median_fc[-1]:.2f}M")
print(f"- IC (5%-95%):    [${p05_fc[-1]:.2f}M, ${p95_fc[-1]:.2f}M]"){python}
</code></pre>
</section>
</section>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-banxico2024expectativas" class="csl-entry" role="listitem">
Banco de México. 2024. <em>Encuesta sobre las Expectativas de los Especialistas en Economía del Sector Privado</em>. Banco de México. <a href="https://www.banxico.org.mx">https://www.banxico.org.mx</a>.
</div>
<div id="ref-cnsf2024panorama" class="csl-entry" role="listitem">
CNSF. 2024. <em>Panorama Analítico del Sector de Seguros y Fianzas 2024</em>. Comisión Nacional de Seguros y Fianzas. <a href="https://sio.cnsf.gob.mx/">https://sio.cnsf.gob.mx/</a>.
</div>
<div id="ref-inegi2024inpc" class="csl-entry" role="listitem">
INEGI. 2024. <em>Índice Nacional de Precios al Consumidor (INPC)</em>. Instituto Nacional de Estadística y Geografía. <a href="https://www.inegi.org.mx/temas/inpc/">https://www.inegi.org.mx/temas/inpc/</a>.
</div>
</div>
</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./metodos-numericos.html" class="pagination-link" aria-label="Métodos Numéricos para EDES">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Métodos Numéricos para EDES</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./resultados_simulacion.html" class="pagination-link" aria-label="resultados_simulacion.html">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">resultados_simulacion.html</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/Mara-DL/Tesis_Maestria/edit/main/modelo-actuarial.qmd" class="toc-action"><i class="bi bi-github"></i>Editar esta página</a></li><li><a href="https://github.com/Mara-DL/Tesis_Maestria/issues/new" class="toc-action"><i class="bi empty"></i>Informar sobre problema</a></li><li><a href="https://github.com/Mara-DL/Tesis_Maestria/blob/main/modelo-actuarial.qmd" class="toc-action"><i class="bi empty"></i>Ver el código</a></li></ul></div></div></div></footer></body></html>